services:
  cerebro:
    image: lmenezes/cerebro:0.9.2
    container_name: cerebro_instance
    ports:
      - "9000:9000"
    networks:
      - elastic_network
    command: 
      - -Dhosts.0.host=http://elasticsearch:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana_instance
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - elastic_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch_master_instance
    environment:
      - cluster.name=elastic_cluster
      - node.name=master
      - network.host=0.0.0.0
      - network.publish_host=192.168.61.171
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=10.32.202.178,192.168.61.171
      - cluster.initial_master_nodes=192.168.61.171
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elk/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_network

volumes:
  elastic_data:
    driver: local

networks:
  elastic_network:
    driver: bridge
