metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.modules:
- module: system
  metricsets:
    - "cpu"
    - "memory"
    - "network"
  period: 10s
  enabled: true
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    #- "memory"
    #- "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: false

output.elasticsearch:
  hosts: ['elasticsearch:9200']